import { WidgetInfo } from '../widget';

export var logo = `    ____    _     _                         _ 
   / __ \\  | |_  (_) __  __  _   _    ___  | |
  / / _\` | | __| | | \\ \\/ / | | | |  / _ \\ | |
 | | (_| | | |_  | |  >  <  | |_| | |  __/ | |
  \\ \\__,_|  \\__| |_| /_/\\_\\  \\__, |  \\___| |_|
   \\____/                    |___/\n`;

export const watermark = {
  html(widget: WidgetInfo): string {
    return [
      `<!---`,
      logo,
      `Generated by @Tixyel Widgets SDK`,
      `Widget name: ${widget.config.name}`,
      `Version: ${widget.config.version}`,
      `Description: ${widget.config.description}`,
      `Tags: ${widget.config.metadata?.tags?.join(', ')}`,
      `Made by: ${widget.config.metadata?.author}`,
      widget.config.metadata?.clientId ? `Made for: ${widget.config.metadata?.clientId}` : undefined,
      ...Object.entries(widget.config.metadata || {})
        .filter(([key]) => !['tags', 'author', 'clientId'].includes(key))
        .map(([key, value]) => `${key}: ${value}`),
      ' ',
      'DO NOT EDIT, SHARE OR DISTRIBUTE THIS CODE WITHOUT PERMISSION FROM THE AUTHOR',
      `--->`,
    ]
      .filter(Boolean)
      .join('\n');
  },

  css(widget: WidgetInfo): string {
    return [
      `/**`,
      logo,
      `Generated by @Tixyel Widgets SDK`,
      `Widget name: ${widget.config.name}`,
      `Version: ${widget.config.version}`,
      `Description: ${widget.config.description}`,
      `Tags: ${widget.config.metadata?.tags?.join(', ')}`,
      `Made by: ${widget.config.metadata?.author}`,
      widget.config.metadata?.clientId ? `Made for: ${widget.config.metadata?.clientId}` : undefined,
      ...Object.entries(widget.config.metadata || {})
        .filter(([key]) => !['tags', 'author', 'clientId'].includes(key))
        .map(([key, value]) => `${key}: ${value}`),
      ' ',
      'DO NOT EDIT, SHARE OR DISTRIBUTE THIS CODE WITHOUT PERMISSION FROM THE AUTHOR',
      `*/`,
    ]
      .filter(Boolean)
      .join('\n');
  },

  script(widget: WidgetInfo): string {
    return [
      `/**`,
      logo,
      `Generated by @Tixyel Widgets SDK`,
      `Widget name: ${widget.config.name}`,
      `Version: ${widget.config.version}`,
      `Description: ${widget.config.description}`,
      `Tags: ${widget.config.metadata?.tags?.join(', ')}`,
      `Made by: ${widget.config.metadata?.author}`,
      widget.config.metadata?.clientId ? `Made for: ${widget.config.metadata?.clientId}` : undefined,
      ...Object.entries(widget.config.metadata || {})
        .filter(([key]) => !['tags', 'author', 'clientId'].includes(key))
        .map(([key, value]) => `${key}: ${value}`),
      ' ',
      'DO NOT EDIT, SHARE OR DISTRIBUTE THIS CODE WITHOUT PERMISSION FROM THE AUTHOR',
      `*/`,
    ]
      .filter(Boolean)
      .join('\n');
  },
};
